server:
    port: 8080
    error:
        include-message: always
        include-binding-errors: always
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/helioplis
    config:
        import: db.yml
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
        show-sql: true

